# Generated by Django 5.1.6 on 2025-03-25 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='response_time',
        ),
        migrations.AddField(
            model_name='response',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='response',
            name='option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='poll.option'),
        ),
        migrations.AlterField(
            model_name='response',
            name='poll',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='poll.poll'),
        ),
    ]
