# Generated by Django 5.1.6 on 2025-03-25 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_remove_response_response_time_response_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='poll.option'),
        ),
        migrations.AlterField(
            model_name='response',
            name='poll',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='poll.poll'),
        ),
    ]
